org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties

minecraft_version=26.1.2
minecraft_version_range=[26.1.1,26.1.2]
neo_version=26.1.2.10-beta

## Mod Properties

mod_id=allthemodium
mod_name=AllTheModium
mod_license=All Rights Reserved
mod_version=4.0.0
mod_group_id=net.allthemods.allthemodium

# Dependency Properties

jei_version=29.5.0.26
jade_version=26.0.6+neoforge
geckolib_version=5.5