# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

org.gradle.configuration-cache=true

## Environment Properties

# The Minecraft version must agree with the Forge version to get a valid artifact
minecraft_version=1.21.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.21.1,)
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.195
# The Neo version range can use any version of Neo as bounds
neo_version_range=[21.1.195,)
# The loader version range can only use the major version of FML as bounds
loader_version_range=[2,)
# The mapping channel to use for mappings.
# The default set of supported mapping channels are ["official", "snapshot", "snapshot_nodoc", "stable", "stable_nodoc"].
# Additional mapping channels can be registered through the "channelProviders" extension in a Gradle plugin.
#
# | Channel   | Version              |                                                                                |
# |-----------|----------------------|--------------------------------------------------------------------------------|
# | official  | MCVersion            | Official field/method names from Mojang mapping files                          |
# | parchment | YYYY.MM.DD-MCVersion | Open community-sourced parameter names and javadocs layered on top of official |
#
# You must be aware of the Mojang license when using the 'official' or 'parchment' mappings.
# See more information here: https://github.com/MinecraftForge/MCPConfig/blob/master/Mojang.md
#
# Parchment is an unofficial project maintained by ParchmentMC, separate from Minecraft Forge.
# Additional setup is needed to use their mappings, see https://parchmentmc.org/docs/getting-started
mapping_channel=official
# The mapping version to query from the mapping channel.
# This must match the format required by the mapping channel.
mapping_version=1.21.1


## Mod Properties

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=allthemodium
# The human-readable display name for the mod.
mod_name=Allthemodium
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod_license=All Rights Reserved
# The mod version. See https://semver.org/
mod_version=2.9.7
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=com.thevortex.allthemodium
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod_authors=thevortex, whatthedrunk
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod_description=Allthemodium!.\nBrought to you by AllTheMods!

tweaks=tweaks-364120:6884768
geckolib=geckolib-388172:6304958
mekanism=mekanism-268560:6486993
jei=jei-238222:5437447
potions=potionsmaster-356801:3672775
ato=ato-405593:6118610
byg=byg:3197729
tconstruct=tconstruct:3273213
mantle=mantle:3273201
worldedit=worldedit-225608:3922622
ars_nouveau=ars-nouveau-401955:5995085
curios=curios-309927:6529130
patchouli=patchouli-306770:6164617
jade=jade-324717:6291517