license="${mod_license}"
issueTrackerURL="https://github.com/AllTheMods/AllTheModium/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="thevortex, whatthedrunk"
description='''
Allthemodium!.\nBrought to you by AllTheMods!
'''

[[mixins]]
config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[5.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="alltheores"
    type="required"
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="BOTH"
